### ISSUE TITLE
issues with login

### ISSUE THREAD

**Issue by nils-kt** [Stuyk/altv-discord-auth#5]
Hello, I have 2 issues.  

1. Wrong example emit event
2. Nothing happends after the button click

#### 1.
Its not `discord:BeginAuth` its `discord:Auth`.

#### 2.
When I click on the button to log in, nothing happens. 
In app.js, the value "this.url" in the function "beginAuth" is null. According to this, nothing happens anymore. Tested with the current alt:V release.

**Comment by Stuyk** [comment]
1. https://github.com/Stuyk/altv-discord-auth/blob/b237a44a2925f9fd8aace955e1e6cdb08fb0c6ef/server/verify.js#L8
2. Is a direct symptom of not calling `discord:BeginAuth`.

**Comment by Stuyk** [comment]
Also take note of: https://github.com/Stuyk/altv-discord-auth/blob/b237a44a2925f9fd8aace955e1e6cdb08fb0c6ef/server/verify.js#L15

**Comment by nils-kt** [comment]
Server-wide I use C#.
Therefore, I apologize if I am using it incorrectly.

That's how I'm currently using it (nothing happends):

```cs
[ScriptEvent(ScriptEventType.PlayerConnect)]
public void PlayerConnect(IPlayer player, string reason)
{
    player.Emit("discord:BeginAuth", player);
}
```
If I use "Auth" instead of "discord:BeginAuth" the WebView is displayed,
however I get the null error again so nothing happens.
