### ISSUE TITLE
 Error: Cannot find module 'node:events'

### ISSUE THREAD

**Issue by Meaxgamergamer** [Stuyk/altv-discord-auth#7]
I need help
![Bild_2022-01-09_135733](https://user-images.githubusercontent.com/53114552/148683064-c3f26926-cb02-401c-8451-3bd762fa1742.png)

**Comment by mago1337** [comment]
Hello,

You can solve this by downgrading your `discord.js` version to `12.5.3`. I was not able to fix this through updating Node.JS, which is where a Google search will lead you.
